// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD_your_web_api_key_here',
    appId: '1:375647894381:web:web_app_id_here',
    messagingSenderId: '375647894381',
    projectId: 'my-g-project-3a7d3',
    authDomain: 'my-g-project-3a7d3.firebaseapp.com',
    storageBucket: 'my-g-project-3a7d3.firebasestorage.app',
    measurementId: 'G-your_measurement_id',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCuvr2k66LFeBpRHGPxz1ZZJCRmIk3fk5c',
    appId: '1:375647894381:android:145b7a7687d5ad3f86f864',
    messagingSenderId: '375647894381',
    projectId: 'my-g-project-3a7d3',
    storageBucket: 'my-g-project-3a7d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_your_ios_api_key_here',
    appId: '1:375647894381:ios:ios_app_id_here',
    messagingSenderId: '375647894381',
    projectId: 'my-g-project-3a7d3',
    storageBucket: 'my-g-project-3a7d3.firebasestorage.app',
    iosBundleId: 'com.example.gProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_your_macos_api_key_here',
    appId: '1:375647894381:ios:ios_app_id_here',
    messagingSenderId: '375647894381',
    projectId: 'my-g-project-3a7d3',
    storageBucket: 'my-g-project-3a7d3.firebasestorage.app',
    iosBundleId: 'com.example.gProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD_your_windows_api_key_here',
    appId: '1:375647894381:web:windows_app_id_here',
    messagingSenderId: '375647894381',
    projectId: 'my-g-project-3a7d3',
    authDomain: 'my-g-project-3a7d3.firebaseapp.com',
    storageBucket: 'my-g-project-3a7d3.firebasestorage.app',
    measurementId: 'G-your_measurement_id',
  );
}
